apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-aggregator
  template:
    metadata:
      labels:
        app: news-aggregator
    spec:
      containers:
      - name: news-aggregator
        image: bhoomika714442/news-aggregator:latest
        ports:
        - containerPort: 5000

